"use client";
import { useCallback, useEffect, useState } from 'react';
import { Plus, Pencil, MessageCircle, Trash2 } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { anniversaryDays, type Anniversary } from '@/lib/life';
import { LifeModal } from './life-ui';
import { Discussion } from './discussion';
const blank={title:'',event_date:'',repeats_yearly:true,emoji:'💕',note:''};
const templates=[
  {zh:'生日',en:'Birthday',emoji:'🎂'},
  {zh:'在一起第一天',en:'Our first day together',emoji:'💕'},
  {zh:'初次见面',en:'The day we met',emoji:'🌷'},
  {zh:'第一次约会',en:'Our first date',emoji:'💐'},
  {zh:'结婚纪念日',en:'Wedding anniversary',emoji:'💍'},
  {zh:'第一次旅行',en:'Our first trip',emoji:'✈️'},
];
export function Anniversaries({spaceId,zh}:{spaceId:string;zh:boolean}){
  const [loaded,setLoaded]=useState(false);
  const [rows,setRows]=useState<Anniversary[]>([]),[edit,setEdit]=useState<Partial<Anniversary>|null>(null),[talk,setTalk]=useState<Anniversary|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[deleteId,setDeleteId]=useState('');
  const load=useCallback(async()=>{if(!supabase)return;const {data,error}=await supabase.from('anniversaries').select('*').eq('space_id',spaceId).order('event_date');if(error)setError(zh?'纪念日加载失败。':'Could not load dates.');else setRows(data||[]);setLoaded(true);},[spaceId,zh]);
  useEffect(()=>{void load();const timer=window.setInterval(load,15000);return()=>window.clearInterval(timer);},[load]);
  async function save(e:React.FormEvent){e.preventDefault();if(!supabase||!edit||busy)return;setBusy(true);setError('');try{const payload={title:edit.title?.trim(),event_date:edit.event_date,repeats_yearly:edit.repeats_yearly,emoji:edit.emoji,note:edit.note};const {data:{user}}=await supabase.auth.getUser();if(!user)throw Error();const result=edit.id?await supabase.from('anniversaries').update(payload).eq('id',edit.id):await supabase.from('anniversaries').insert({...payload,space_id:spaceId,created_by:user.id});if(result.error)throw result.error;setEdit(null);await load();}catch{setError(zh?'保存失败，请重试。':'Could not save date.');}finally{setBusy(false);}}
  async function remove(){if(!supabase||busy)return;setBusy(true);setError('');const {error}=await supabase.from('anniversaries').delete().eq('id',deleteId);if(error)setError(zh?'删除失败。':'Could not delete.');else{setDeleteId('');await load();}setBusy(false);}
  function startTemplate(template:typeof templates[number]){setError('');setEdit({...blank,title:zh?template.zh:template.en,emoji:template.emoji});}
  const ordered=[...rows].sort((a,b)=>{const da=anniversaryDays(a.event_date,a.repeats_yearly),db=anniversaryDays(b.event_date,b.repeats_yearly);return (da<0?Infinity:da)-(db<0?Infinity:db);});
  return <section className="life-section"><div className="life-section-head"><div><span className="eyebrow">OUR SPECIAL DAYS</span><h2>{zh?'值得记住的日子':'Dates close to our hearts'}</h2></div><button className="secondary" onClick={()=>{setError('');setEdit({...blank});}}><Plus size={15}/>{zh?'添加纪念日':'Add a date'}</button></div>
    {!loaded&&<p className="life-muted">{zh?'正在加载纪念日…':'Loading dates…'}</p>}{loaded&&!rows.length&&!error&&<p className="life-empty">{zh?'生日、第一次约会、结婚纪念日……都可以放在这里。':'Birthdays, first dates, anniversaries… keep them all here.'}</p>}
    <div className="anniversary-presets"><p className="life-muted">{zh?'从一个特别的日子开始 · 选好后填写日期':'Start with a special day · choose a template, then a date'}</p><div className="anniversary-template-grid">{templates.map(template=><button className="anniversary-template" type="button" key={template.en} onClick={()=>startTemplate(template)}><span aria-hidden="true">{template.emoji}</span>{zh?template.zh:template.en}<Plus size={13} aria-hidden="true"/></button>)}</div></div>
    <div className="anniversary-grid">{ordered.map(row=>{const days=anniversaryDays(row.event_date,row.repeats_yearly);return <article className="anniversary-card" key={row.id}><span className="anniversary-emoji">{row.emoji}</span><strong>{row.title}</strong><span className="anniversary-count">{days===0?(zh?'就是今天！':'Today!'):days>0?(zh?`还有 ${days} 天`:`In ${days} days`):(zh?`已过去 ${-days} 天`:`${-days} days ago`)}</span><small>{row.event_date}{row.repeats_yearly?(zh?' · 每年':' · Every year'):''}</small>{row.note&&<p>{row.note}</p>}<div className="life-actions"><button className="text-action" onClick={()=>setTalk(row)}><MessageCircle size={14}/>{zh?'留言':'Comments'}</button><button className="icon-button" aria-label={`${zh?'编辑':'Edit'} ${row.title}`} onClick={()=>{setError('');setEdit(row);}}><Pencil size={14}/></button><button className="icon-button" aria-label={`${zh?'删除':'Delete'} ${row.title}`} onClick={()=>setDeleteId(row.id)}><Trash2 size={14}/></button></div></article>;})}</div>
    {error&&!edit&&<p role="alert" className="form-error">{error}</p>}
    {edit&&<LifeModal title={zh?'我们的纪念日':'Our special date'} onClose={()=>{if(!busy)setEdit(null);}}><form onSubmit={save}>{!edit.id&&<label>{zh?'常用模板':'Quick template'}<select value="" onChange={e=>{const template=templates.find(t=>t.en===e.target.value);if(template)setEdit({...edit,title:zh?template.zh:template.en,emoji:template.emoji,repeats_yearly:true});}}><option value="" disabled>{zh?'选择模板，也可以直接自定义':'Choose a template or write your own'}</option>{templates.map(t=><option key={t.en} value={t.en}>{t.emoji} {zh?t.zh:t.en}</option>)}</select></label>}<label>{zh?'名称':'Title'}<input required maxLength={80} value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})}/></label><p className="life-muted">{zh?'名称可以自由修改，例如“小明的生日”，两个人的生日可以分别添加。':"Make the title yours, like Alex’s birthday. Add a separate date for each partner."}</p><label>{zh?'日期':'Date'}<input required type="date" value={edit.event_date} onChange={e=>setEdit({...edit,event_date:e.target.value})}/></label><label className="check-label"><input type="checkbox" checked={edit.repeats_yearly} onChange={e=>setEdit({...edit,repeats_yearly:e.target.checked})}/>{zh?'每年重复':'Count down every year'}</label><div className="emoji-options">{['💕','🎂','💍','✈️','🎉','🌷','💐'].map(emoji=><button type="button" aria-pressed={edit.emoji===emoji} key={emoji} onClick={()=>setEdit({...edit,emoji})}>{emoji}</button>)}</div><label>{zh?'想记住的话':'A little note'}<textarea maxLength={1000} value={edit.note} onChange={e=>setEdit({...edit,note:e.target.value})}/></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{zh?'保存纪念日':'Save date'}</button></form></LifeModal>}
    {talk&&<LifeModal title={`${talk.emoji} ${talk.title}`} onClose={()=>setTalk(null)}><Discussion spaceId={spaceId} target={{anniversary_id:talk.id}} zh={zh}/></LifeModal>}
    {deleteId&&<LifeModal title={zh?'删除这个纪念日？':'Delete this date?'} onClose={()=>setDeleteId('')}><p>{zh?'这个日子和下面的留言会一起删除。':'This date and its comments will be removed.'}</p><button className="primary" disabled={busy} onClick={()=>void remove()}>{zh?'确认删除':'Delete date'}</button></LifeModal>}
  </section>;
}
