"use client";
import { useState } from 'react';
import { Camera } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { prepareBackgroundPhoto } from '@/lib/photo';
import { localToday, type LifeMember } from '@/lib/life';
import { LifeModal } from './life-ui';
export type SpaceProfile={id:string;name:string;signature?:string;together_since?:string|null};
export function CoupleProfile({space,member,zh,onClose,onSaved}:{space:SpaceProfile;member:LifeMember;zh:boolean;onClose:()=>void;onSaved:(space:SpaceProfile,member:LifeMember)=>void}){
 const [name,setName]=useState(member.display_name||''),[avatar,setAvatar]=useState(member.custom_avatar||null),[spaceName,setSpaceName]=useState(space.name),[signature,setSignature]=useState(space.signature||''),[since,setSince]=useState(space.together_since||''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function choose(file:File){setBusy(true);setError('');try{setAvatar(await prepareBackgroundPhoto(file,320,100000));}catch{setError(zh?'请选择 15 MB 以内的 JPG、PNG 或 WebP 照片。':'Choose a JPG, PNG or WebP photo under 15 MB.');}finally{setBusy(false);}}
 async function save(e:React.FormEvent){e.preventDefault();if(!supabase||busy)return;setBusy(true);setError('');try{const profile=await supabase.from('space_members').update({display_name:name.trim(),custom_avatar:avatar,profile_customized:true}).eq('user_id',member.user_id).eq('space_id',space.id);if(profile.error)throw profile.error;const next={...space,name:spaceName.trim(),signature:signature.trim(),together_since:since||null};const result=await supabase.from('couple_spaces').update({name:next.name,signature:next.signature,together_since:next.together_since}).eq('id',space.id);if(result.error)throw result.error;onSaved(next,{...member,display_name:name.trim(),custom_avatar:avatar});window.dispatchEvent(new Event('life-changed'));onClose();}catch{setError(zh?'保存未完成，请重试。':'Save did not complete. Please retry.');}finally{setBusy(false);}}
 return <LifeModal title={zh?'装扮我们的小世界':'Make this space yours'} onClose={()=>{if(!busy)onClose();}}><form onSubmit={save}><div className="profile-photo-editor">{(avatar||member.avatar_url)&&<img src={avatar||member.avatar_url} alt={zh?'我的头像':'My avatar'} referrerPolicy="no-referrer"/>}<label className="secondary photo-upload-label"><Camera size={15}/>{zh?'换头像':'Change avatar'}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void choose(file);}}/></label>{avatar&&<button type="button" className="text-action" onClick={()=>setAvatar(null)}>{zh?'使用 Google 头像':'Use Google avatar'}</button>}</div><label>{zh?'我的昵称':'My nickname'}<input required maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><label>{zh?'空间名字':'Space name'}<input required maxLength={80} value={spaceName} onChange={e=>setSpaceName(e.target.value)}/></label><label>{zh?'我们的签名':'Our little motto'}<input maxLength={160} value={signature} onChange={e=>setSignature(e.target.value)} placeholder={zh?'一起把平凡的日子过得闪闪发光':'Finding magic in the everyday'}/></label><label>{zh?'在一起的第一天':'Our first day together'}<input type="date" max={localToday()} value={since} onChange={e=>setSince(e.target.value)}/></label><small className="life-muted">{zh?'昵称和头像只修改自己；空间名字、签名和日期两个人共享。':'Edit your own name and photo. The space name, motto and date are shared.'}</small>{error&&<p role="alert" className="form-error">{error}</p>}<button className="primary" disabled={busy}>{zh?'保存资料':'Save profile'}</button></form></LifeModal>;
}
