'use client';
import {useEffect,useState} from 'react';
import {LifeModal} from './life-ui';
export const sections=['wishes','map','pet','done','life','adventure','dashboard'] as const;
export type Section=typeof sections[number];
export function sectionName(view:Section,zh:boolean){return ({wishes:['心愿','Wishes'],map:['地图','Map'],pet:['小窝','Pets'],done:['做过的事','Things we did'],life:['纪念日与相册','Dates & memories'],adventure:['一起冒险','Adventures'],dashboard:['概览','Overview']}[view])[zh?0:1];}
const key='wish-together:layout:v1';
export function useLayoutPreferences(){const [tabs,setTabs]=useState<Section[]>(['wishes','map','pet']),[density,setDensity]=useState('comfortable'),[loaded,setLoaded]=useState(false),[error,setError]=useState(false);
 useEffect(()=>{try{const p=JSON.parse(localStorage.getItem(key)||'null');if(p){const valid=Array.isArray(p.tabs)?[...new Set<Section>(p.tabs.filter((x:Section)=>sections.includes(x)))]:[];if(valid.length&&valid.length<=5)setTabs(valid);if(['comfortable','compact'].includes(p.density))setDensity(p.density);}}catch{}setLoaded(true);},[]);
 useEffect(()=>{if(loaded)try{localStorage.setItem(key,JSON.stringify({tabs,density}));setError(false);}catch{setError(true);}},[tabs,density,loaded]);return {tabs,setTabs,density,setDensity,error};}
export function LayoutPreferences({prefs,zh,onClose,onAppearance}:{prefs:ReturnType<typeof useLayoutPreferences>;zh:boolean;onClose:()=>void;onAppearance:()=>void}){return <LifeModal title={zh?'按自己的习惯':'Make it yours'} onClose={onClose}><p className="life-muted">{zh?'偏好仅保存在此设备；其他栏目一直可以从“更多”进入。':'Saved on this device. Every section remains available in More.'}</p><fieldset><legend>{zh?'常用栏目（1–5 个，按选择顺序排列）':'Main sections (1–5, in selection order)'}</legend>{sections.map(s=><label className="check-label" key={s}><input type="checkbox" checked={prefs.tabs.includes(s)} disabled={!prefs.tabs.includes(s)&&prefs.tabs.length>=5||prefs.tabs.includes(s)&&prefs.tabs.length===1} onChange={e=>prefs.setTabs(e.target.checked?[...prefs.tabs,s]:prefs.tabs.filter(x=>x!==s))}/>{sectionName(s,zh)}{prefs.tabs.includes(s)&&` · ${prefs.tabs.indexOf(s)+1}`}</label>)}</fieldset><label>{zh?'心愿卡片大小':'Wish card size'}<select value={prefs.density} onChange={e=>prefs.setDensity(e.target.value)}><option value="comfortable">{zh?'舒展':'Comfortable'}</option><option value="compact">{zh?'紧凑':'Compact'}</option></select></label><button className="secondary" onClick={onAppearance}>{zh?'背景照片与主题':'Background & theme'}</button><button className="text-action" onClick={()=>{prefs.setTabs(['wishes','map','pet']);prefs.setDensity('comfortable');}}>{zh?'恢复默认布局':'Reset layout'}</button>{prefs.error&&<p role="alert">{zh?'此设备无法保存偏好，刷新后可能恢复默认。':'Could not save preferences on this device.'}</p>}</LifeModal>;}
