"use client";
import { useCallback, useEffect, useState } from 'react';
import { Camera, ImagePlus, Trash2 } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { prepareAlbumPhoto } from '@/lib/photo';
import { localToday, type LifeWish } from '@/lib/life';
import { LifeModal } from './life-ui';
import { Discussion } from './discussion';
const BUCKET='couple-memories';
type Memory={id:string;space_id:string;wish_id:string|null;caption:string;taken_on:string;photo_ready:boolean;byte_size:number};
function path(m:Pick<Memory,'id'|'space_id'>,thumb=false){return `${m.space_id}/${m.id}/${thumb?'thumb':'photo'}.jpg`;}
function PrivatePhoto({memory,thumb=false}:{memory:Memory;thumb?:boolean}){
  const [src,setSrc]=useState(''),[failed,setFailed]=useState(false),[retry,setRetry]=useState(0);
  useEffect(()=>{let active=true;async function sign(){const result=await supabase?.storage.from(BUCKET).createSignedUrl(path(memory,thumb),3600);if(!active)return;if(result?.error||!result?.data){setFailed(true);return;}setFailed(false);setSrc(result.data.signedUrl);}void sign();const timer=window.setInterval(sign,3000000);return()=>{active=false;window.clearInterval(timer);};},[memory.id,memory.space_id,thumb,retry]);
  return failed?<button className="photo-retry" onClick={()=>setRetry(n=>n+1)}>重新加载 / Retry</button>:src?<img src={src} loading="lazy" alt={memory.caption||'Our memory'} onError={()=>setFailed(true)}/>:<span className="photo-placeholder"><Camera size={24}/></span>;
}
export function Memories({spaceId,zh,wishes,wishId,onBackground}:{spaceId:string;zh:boolean;wishes:LifeWish[];wishId?:string;onBackground:(photo:string)=>Promise<void>}){
  const [loaded,setLoaded]=useState(false);
  const [rows,setRows]=useState<Memory[]>([]),[page,setPage]=useState(0),[count,setCount]=useState(0),[total,setTotal]=useState(0),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [adding,setAdding]=useState(false),[selected,setSelected]=useState<Memory|null>(null),[deleting,setDeleting]=useState<Memory|null>(null),[notice,setNotice]=useState('');
  const [draft,setDraft]=useState<Awaited<ReturnType<typeof prepareAlbumPhoto>>|null>(null),[caption,setCaption]=useState(''),[date,setDate]=useState(localToday()),[linked,setLinked]=useState(wishId||'');
  const load=useCallback(async()=>{if(!supabase)return;let q=supabase.from('memories').select('id,space_id,wish_id,caption,taken_on,photo_ready,byte_size',{count:'exact'}).eq('space_id',spaceId);if(wishId)q=q.eq('wish_id',wishId);const {data,error,count}=await q.order('taken_on',{ascending:false}).order('created_at',{ascending:false}).range(page*12,page*12+11);if(error){setError(zh?'相册加载失败，请重试。':'Could not load the album.');return;}setRows(data||[]);setCount(count||0);setLoaded(true);const all=await supabase.from('memories').select('id',{head:true,count:'exact'}).eq('space_id',spaceId);if(!all.error)setTotal(all.count||0);},[spaceId,wishId,page,zh]);
  useEffect(()=>{void load();const timer=window.setInterval(load,20000);return()=>window.clearInterval(timer);},[load]);
  async function choose(file:File){setBusy(true);setError('');try{setDraft(await prepareAlbumPhoto(file));}catch{setError(zh?'请选择 15 MB 以内的 JPG、PNG 或 WebP 照片。':'Choose a JPG, PNG or WebP photo under 15 MB.');}finally{setBusy(false);}}
  async function upload(e:React.FormEvent){e.preventDefault();if(!supabase||!draft||busy)return;setBusy(true);setError('');const client=supabase;const id=crypto.randomUUID(),memory={id,space_id:spaceId};let reserved=false;try{const {data:{user}}=await client.auth.getUser();if(!user)throw Error();const record=await client.from('memories').insert({...memory,created_by:user.id,wish_id:linked||null,caption:caption.trim(),taken_on:date,byte_size:draft.blob.size+draft.thumbnail.size});if(record.error)throw record.error;reserved=true;
    const photo=await client.storage.from(BUCKET).upload(path(memory),draft.blob,{contentType:'image/jpeg',upsert:false});if(photo.error)throw photo.error;
    const thumb=await client.storage.from(BUCKET).upload(path(memory,true),draft.thumbnail,{contentType:'image/jpeg',upsert:false});if(thumb.error)throw thumb.error;
    const ready=await client.from('memories').update({photo_ready:true}).eq('id',id);if(ready.error)throw ready.error;
    setAdding(false);setDraft(null);setCaption('');setPage(0);await load();
  }catch{if(reserved){const cleanup=await client.storage.from(BUCKET).remove([path(memory),path(memory,true)]);if(!cleanup.error)await client.from('memories').delete().eq('id',id);}setError(zh?'上传失败或相册已满，照片预览已保留，可重试。':'Upload failed or album is full. Your preview is kept for retry.');await load();}finally{setBusy(false);}}
  async function remove(){if(!supabase||!deleting||busy)return;setBusy(true);setError('');try{const files=await supabase.storage.from(BUCKET).remove([path(deleting),path(deleting,true)]);if(files.error)throw files.error;const row=await supabase.from('memories').delete().eq('id',deleting.id);if(row.error)throw row.error;setDeleting(null);setSelected(null);if(rows.length===1&&page>0)setPage(p=>p-1);else await load();}catch{setError(zh?'删除失败，请重试。':'Could not remove photo. Please retry.');}finally{setBusy(false);}}
  async function useBackground(){if(!supabase||!selected||busy)return;setBusy(true);setError('');setNotice('');try{const {data,error}=await supabase.storage.from(BUCKET).download(path(selected));if(error||!data)throw error;const photo=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(data);});await onBackground(photo);setNotice(zh?'已设为你们的背景。':'Now your shared background.');}catch{setError(zh?'背景设置失败，请重试。':'Could not set the background.');}finally{setBusy(false);}}
  return <section className="life-section"><div className="life-section-head"><div><span className="eyebrow">LITTLE MOMENTS, FOREVER</span><h2>{zh?'我们的回忆相册':'Our memory album'}</h2><p className="life-muted">{zh?`${total}/200 张 · 每张大图最多 500 KB，私密保存`:`${total}/200 photos · Up to 500 KB each, kept private`}</p></div><button className="secondary" disabled={total>=200} onClick={()=>{setError('');setDraft(null);setCaption('');setDate(localToday());setLinked(wishId||'');setAdding(true);}}><ImagePlus size={16}/>{zh?'存一张回忆':'Add a memory'}</button></div>
    {!loaded&&<p className="life-muted">{zh?'正在加载回忆…':'Loading memories…'}</p>}{loaded&&!rows.length&&!error&&<p className="life-empty">{zh?'把一次约会、一段旅程，留在这里。':'Save a date, a trip, a moment together.'}</p>}
    <div className="memory-grid">{rows.map(m=><article className="memory-card" key={m.id}>{m.photo_ready?<button className="memory-image" onClick={()=>{setError('');setNotice('');setSelected(m);}}><PrivatePhoto memory={m} thumb/></button>:<div className="photo-placeholder">{zh?'上传未完成':'Upload incomplete'}</div>}<div><time>{m.taken_on}</time><p>{m.caption||wishes.find(w=>w.id===m.wish_id)?.title||(zh?'一起的小日常':'A little moment together')}</p><button className="icon-button" aria-label={zh?'删除回忆照片':'Delete memory photo'} onClick={()=>{setError('');setDeleting(m);}}><Trash2 size={14}/></button></div></article>)}</div>
    {count>12&&<div className="album-pagination"><button className="secondary" disabled={page===0} onClick={()=>setPage(p=>p-1)}>{zh?'上一页':'Previous'}</button><span>{page+1} / {Math.ceil(count/12)}</span><button className="secondary" disabled={(page+1)*12>=count} onClick={()=>setPage(p=>p+1)}>{zh?'下一页':'Next'}</button></div>}
    {error&&!adding&&!selected&&!deleting&&<p className="form-error" role="alert">{error}</p>}
    {adding&&<LifeModal title={zh?'存下一张回忆':'Save a memory'} onClose={()=>{if(!busy)setAdding(false);}}><form onSubmit={upload}><label className="photo-upload-label secondary"><Camera size={16}/>{busy?(zh?'处理中…':'Working…'):(zh?'选择照片':'Choose photo')}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void choose(file);}}/></label>{draft&&<><img className="background-photo-preview" src={draft.data} alt={zh?'待上传照片':'Photo preview'}/><small className="life-muted">{Math.ceil((draft.blob.size+draft.thumbnail.size)/1024)} KB · {zh?'已压缩，原图不上传':'Compressed; original stays on your device'}</small></>}<label>{zh?'哪一天':'Date'}<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>{zh?'写一句感想':'A little memory'}<textarea maxLength={1000} value={caption} onChange={e=>setCaption(e.target.value)}/></label><label>{zh?'关联心愿（可选）':'Related wish (optional)'}<select value={linked} onChange={e=>setLinked(e.target.value)}><option value="">{zh?'独立的回忆':'Just a memory'}</option>{wishes.map(w=><option key={w.id} value={w.id}>{w.title}</option>)}</select></label>{error&&<p className="form-error" role="alert">{error}</p>}<button className="primary" disabled={busy||!draft}>{zh?'保存到相册':'Save to album'}</button></form></LifeModal>}
    {selected&&<LifeModal title={selected.caption||(zh?'我们的回忆':'Our memory')} onClose={()=>{if(!busy)setSelected(null);}}><div className="memory-full"><PrivatePhoto memory={selected}/></div><p className="life-muted">{selected.taken_on}</p><button className="secondary" disabled={busy} onClick={()=>void useBackground()}>{zh?'用作空间背景':'Use as background'}</button>{notice&&<p role="status">{notice}</p>}{error&&<p role="alert" className="form-error">{error}</p>}<Discussion spaceId={spaceId} target={{memory_id:selected.id}} zh={zh}/></LifeModal>}
    {deleting&&<LifeModal title={zh?'删除这张回忆？':'Delete this memory?'} onClose={()=>{if(!busy)setDeleting(null);}}><p>{zh?'照片和留言会删除，并释放相册空间。':'This removes the photo and comments, freeing album space.'}</p>{error&&<p role="alert" className="form-error">{error}</p>}<button className="primary" disabled={busy} onClick={()=>void remove()}>{zh?'确认删除':'Delete memory'}</button></LifeModal>}
  </section>;
}
