'use client';
import {useEffect,useState} from 'react';
import {XhsLinkCard} from './xhs-link-card';
import {LifeModal} from './life-ui';
import {parseSharedWish,shareIdentity,SHARE_LIMIT,type SharedWish} from '@/lib/share-import';
import type {SyncedWish} from '@/lib/wish-sync';
export function ShareImport({spaceId,zh,raw,onRaw,onClose,onImport,onExisting,onDraft,wishes,hasDraft,ready}:{spaceId:string|null;zh:boolean;raw:string;onRaw:(s:string)=>void;onClose:()=>void;onImport:(s:SharedWish)=>string|void;onExisting:(w:SyncedWish)=>void;onDraft:()=>void;wishes:SyncedWish[];hasDraft:boolean;ready:boolean}){
 const parsed=parseSharedWish(raw),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const duplicate=parsed.url?wishes.find(w=>!w.deletedAt&&shareIdentity(w.url)===shareIdentity(parsed.url)):undefined;
 useEffect(()=>setMessage(''),[raw]);
 async function paste(){setBusy(true);try{if(!navigator.clipboard?.readText)throw Error();const value=await navigator.clipboard.readText();onRaw(value);if(!value.trim())setMessage(zh?'剪贴板是空的，可以直接粘贴到下面。':'Clipboard is empty. Paste below instead.');}catch{setMessage(zh?'浏览器未允许读取，请长按输入框粘贴，或使用粘贴快捷键。':'Clipboard access is unavailable. Paste into the field below.');}finally{setBusy(false);}}
 return <LifeModal title={zh?'收下小红书与链接':'Save a shared idea'} onClose={onClose}><div className="share-import"><p>{zh?'在小红书点“分享 → 复制链接”，把整段文案粘贴过来就好。其他网页链接也可以。':'In Xiaohongshu, tap Share → Copy link, then paste the entire message here. Other web links work too.'}</p><button type="button" className="secondary" disabled={busy} onClick={()=>void paste()}>{zh?'粘贴分享文案':'Paste shared text'}</button><label>{zh?'分享文案或链接':'Shared text or link'}<textarea value={raw} onChange={e=>onRaw(e.target.value)} rows={5} placeholder={zh?'标题、分享口令和链接可以整段粘贴，无需手动删掉多余文字。':'Paste the full message, including its link.'}/></label>{message&&<p role="status">{message}</p>}{raw.length>SHARE_LIMIT&&<p role="alert">{zh?'内容过长，请保留一篇笔记的分享文案（最多 16000 字）。':'Keep one shared note, up to 16,000 characters.'}</p>}{raw.trim()&&<div className="share-import-preview"><span className="eyebrow">{parsed.source==='xiaohongshu'?'小红书 · REDNOTE':parsed.source==='web'?'WEB LINK':'A LITTLE IDEA'}</span>{parsed.source==='xiaohongshu'?<XhsLinkCard key={parsed.url} url={parsed.url} title={parsed.title} spaceId={spaceId} zh={zh}/>:<><h3>{parsed.title}</h3>{parsed.url&&<p className="share-import-url">{parsed.url}</p>}</>}{parsed.address&&<p>📍 {parsed.address}</p>}<small>{zh?'会尝试读取公开标题和封面；无法读取时保留分享标题和原链接。':'Public titles and covers are shown when available. Otherwise, your shared title and original link are kept.'}</small>{parsed.links.length>1&&<p>{zh?'发现多个链接，请一次只导入一个，避免选错笔记。':'Multiple links found. Keep one link to avoid importing the wrong note.'}</p>}</div>}{duplicate&&<div className="share-import-warning"><p>{zh?`已经收过这条链接：「${duplicate.title}」`:`Already saved: ${duplicate.title}`}</p><button type="button" className="secondary" onClick={()=>onExisting(duplicate)}>{zh?'查看已有心愿':'Open existing wish'}</button></div>}{hasDraft&&<div className="share-import-warning"><p>{zh?'你还有一个未完成的新心愿草稿，先继续保存或放弃它，再导入这条。分享文案会保留在当前标签页。':'You have an unfinished new wish. Save or discard that draft first. Your shared text stays in this tab.'}</p><button type="button" className="secondary" onClick={onDraft}>{zh?'继续之前的草稿':'Continue previous draft'}</button></div>}<button type="button" className="primary" disabled={!ready||!raw.trim()||raw.length>SHARE_LIMIT||hasDraft||parsed.links.length>1} onClick={()=>{const error=onImport(parsed);if(error)setMessage(error);}}>{duplicate?(zh?'仍作为新心愿编辑':'Edit as another wish'):(zh?'带入心愿，确认保存':'Review as a wish')}</button><div className="share-import-help"><strong>{zh?'下次怎么更快？':'A quicker route next time'}</strong><p>{zh?'iPhone：复制分享文案，回到这里粘贴。支持系统分享的 Android / Chrome 设备：安装到主屏幕后，可尝试在分享菜单选择 Wish Together；没有出现时用复制粘贴即可。':'iPhone: copy the shared text and paste here. On supported Android / Chrome devices, install the app and look for Wish Together in the system share menu. Copy and paste works when it is unavailable.'}</p><small>{zh?'无需登录小红书，不会读取你的收藏夹。':'No Xiaohongshu login or access to your saved collection.'}</small></div></div></LifeModal>;
}
