"use client";
import { useEffect, useState } from 'react';
import { supabase } from '@/lib/supabase';
import type { LifeMember, LifeWish, WishPlan } from '@/lib/life';
import { LifeModal } from './life-ui';
import { Discussion } from './discussion';
import { Memories } from './memories';
export function WishExperience({spaceId,wish,wishes,zh,onClose,onBackground}:{spaceId:string;wish:LifeWish;wishes:LifeWish[];zh:boolean;onClose:()=>void;onBackground:(photo:string)=>Promise<void>}){
 const [plan,setPlan]=useState<WishPlan>({wish_id:wish.id,date_on:wish.plannedDate||null,budget:null,currency:'USD',owner_task:'',partner_task:''}),[exists,setExists]=useState(false),[ready,setReady]=useState(false),[members,setMembers]=useState<LifeMember[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 useEffect(()=>{let active=true;async function load(){const result=await supabase?.from('wish_plans').select('*').eq('wish_id',wish.id).maybeSingle();if(!active)return;if(result?.error){setError(zh?'约会计划加载失败，请重新打开。':'Could not load plan. Please reopen.');return;}if(result?.data){setPlan({...result.data,date_on:wish.plannedDate||null});setExists(true);}setReady(true);const m=await supabase?.from('space_members').select('user_id,role,display_name,avatar_url').eq('space_id',spaceId);if(active)setMembers(m?.data||[]);}void load();return()=>{active=false;};},[wish.id,spaceId,zh]);
 async function save(e:React.FormEvent){e.preventDefault();if(!supabase||busy||!ready)return;setBusy(true);setError('');setNotice('');try{const {wish_id,...payload}=plan;const result=exists?await supabase.from('wish_plans').update(payload).eq('wish_id',wish.id):await supabase.from('wish_plans').insert({...payload,wish_id,space_id:spaceId});if(result.error)throw result.error;setExists(true);const wishUpdate=await supabase.from('wishes').update({planned_date:plan.date_on,status:plan.date_on?'planned':wish.status}).eq('id',wish.id).neq('status','done');if(wishUpdate.error)throw wishUpdate.error;setNotice(zh?'约会计划已保存，两个人都能看到。':'Date plan saved for both of you.');window.dispatchEvent(new Event('life-changed'));}catch{setError(zh?'保存失败，请重试。':'Could not save plan.');}finally{setBusy(false);}}
 return <LifeModal title={wish.title} onClose={()=>{if(!busy)onClose();}}>{wish.status!=='done'&&<section className="date-plan"><h3>{zh?'一起安排这次约会':'Plan this little adventure'}</h3><form onSubmit={save}><div className="life-form-grid"><label>{zh?'约会日期':'Date'}<input type="date" value={plan.date_on||''} onChange={e=>setPlan({...plan,date_on:e.target.value||null})}/></label><label>{zh?'预算（可选）':'Budget (optional)'}<input type="number" min="0" max="9999999999.99" step="0.01" value={plan.budget??''} onChange={e=>setPlan({...plan,budget:e.target.value===''?null:Number(e.target.value)})}/></label><label>{zh?'币种':'Currency'}<select value={plan.currency} onChange={e=>setPlan({...plan,currency:e.target.value})}>{['USD','CNY','EUR','GBP','JPY','CAD','AUD'].map(c=><option key={c}>{c}</option>)}</select></label></div><label>{members.find(m=>m.role==='owner')?.display_name||(zh?'空间创建者':'Space owner')} · {zh?'负责什么':'Taking care of'}<textarea maxLength={500} rows={2} value={plan.owner_task} onChange={e=>setPlan({...plan,owner_task:e.target.value})} placeholder={zh?'订餐厅、买电影票……':'Book dinner, get tickets…'}/></label><label>{members.find(m=>m.role==='partner')?.display_name||(zh?'另一半':'Partner')} · {zh?'负责什么':'Taking care of'}<textarea maxLength={500} rows={2} value={plan.partner_task} onChange={e=>setPlan({...plan,partner_task:e.target.value})}/></label><button className="primary" disabled={busy||!ready}>{zh?'保存约会安排':'Save date plan'}</button></form>{notice&&<p role="status">{notice}</p>}{error&&<p role="alert" className="form-error">{error}</p>}</section>}
 <Discussion spaceId={spaceId} target={{wish_id:wish.id}} zh={zh}/>
 {wish.status==='done'&&<Memories spaceId={spaceId} wishes={wishes} wishId={wish.id} zh={zh} onBackground={onBackground}/>}
 </LifeModal>;
}
