'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,Image as ImageIcon} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import {isRedNote,safeShareUrl} from '@/lib/share-import';
export type LinkPreview={title:string;description:string;image:string;url:string};
const cache=new Map<string,{expires:number;preview:LinkPreview|null}>();
const pending=new Map<string,Promise<LinkPreview|null>>();
function validPreview(value:unknown):LinkPreview|null{if(!value||typeof value!=='object')return null;const p=value as LinkPreview;if(typeof p.title!=='string'||!p.title.trim()||typeof p.description!=='string'||typeof p.image!=='string'||typeof p.url!=='string'||!isRedNote(p.url)||!safeShareUrl(p.url))return null;let image='';try{const u=new URL(p.image);if(u.protocol==='https:'&&!u.port&&!u.username&&!u.password&&(/(^|\.)xhscdn\.com$/.test(u.hostname)||u.hostname==='ci.xiaohongshu.com'))image=u.href;}catch{}return {title:p.title.slice(0,300),description:p.description.slice(0,600),image,url:p.url};}
export function XhsLinkCard({url,title,note='',spaceId,zh,onPreview}:{url:string;title:string;note?:string;spaceId:string|null;zh:boolean;onPreview?:(preview:LinkPreview|null)=>void}){
 const [preview,setPreview]=useState<LinkPreview|null>(null),[status,setStatus]=useState<'idle'|'loading'|'ready'|'unavailable'>('idle'),[broken,setBroken]=useState(false),[retry,setRetry]=useState(0),[visible,setVisible]=useState(false);const ref=useRef<HTMLDivElement>(null),callback=useRef(onPreview);callback.current=onPreview;
 useEffect(()=>{if(!ref.current)return;const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){setVisible(true);observer.disconnect();}},{rootMargin:'150px'});observer.observe(ref.current);return()=>observer.disconnect();},[url]);
 useEffect(()=>{let active=true;setPreview(null);setBroken(false);callback.current?.(null);if(!visible||!url||!isRedNote(url)){setStatus('idle');return;}if(!supabase||!spaceId){setStatus('unavailable');return;}const client=supabase;setStatus('loading');const timer=setTimeout(()=>{void(async()=>{try{const {data:{session}}=await client.auth.getSession();if(!session)throw Error();const key=`${session.user.id}:${spaceId}:${url}`,known=cache.get(key);let result:LinkPreview|null;if(!retry&&known&&known.expires>Date.now())result=known.preview;else{let task=pending.get(key);if(!task){task=client.functions.invoke('xhs-preview',{body:{url,spaceId}}).then(({data,error})=>{if(error)throw error;const value=validPreview(data?.preview);if(cache.size>=150)cache.delete(cache.keys().next().value!);cache.set(key,{expires:Date.now()+(value?1800000:60000),preview:value});return value;}).finally(()=>pending.delete(key));pending.set(key,task);}result=await task;}if(active){setPreview(result);setStatus(result?'ready':'unavailable');callback.current?.(result);}}catch{if(active)setStatus('unavailable');}})();},500);return()=>{active=false;clearTimeout(timer);};},[url,spaceId,visible,retry]);
 if(!isRedNote(url)||!safeShareUrl(url))return null;
 const cover=preview?.image&&!broken?preview.image:'';
 return <div className="xhs-link-preview" ref={ref}><a className="xhs-link-card" href={url} target="_blank" rel="noopener noreferrer" aria-label={zh?`在小红书打开：${preview?.title||title}`:`Open in Xiaohongshu: ${preview?.title||title}`}><div className={`xhs-link-cover ${cover?'':'is-placeholder'}`}>{cover?<img src={cover} alt="" loading="lazy" referrerPolicy="no-referrer" onError={()=>setBroken(true)}/>:<><ImageIcon size={25}/><span>{zh?'小红书笔记':'Xiaohongshu note'}</span></>}</div><div className="xhs-link-content"><h3>{preview?.title||title||(zh?'小红书里的一个心愿':'A Xiaohongshu idea')}</h3>{(preview?.description||note)&&<p>{preview?.description||note}</p>}<span><b>小红书</b><small>{zh?'查看原笔记':'View original'}</small><ArrowUpRight size={14}/></span></div></a><div className="xhs-link-status">{status==='loading'?<small role="status">{zh?'正在读取链接预览…':'Loading link preview…'}</small>:status==='unavailable'||broken?<><small>{zh?'暂时未能读取完整预览，原链接仍可打开。':'Full preview unavailable. You can still open the original.'}</small>{spaceId&&<button type="button" className="text-action" onClick={()=>setRetry(v=>v+1)}>{zh?'重试':'Retry'}</button>}</>:!preview?.image&&status==='ready'?<small>{zh?'这条笔记暂未提供可用封面。':'No cover available for this note.'}</small>:null}</div></div>;
}
